### ISSUE TITLE
ci: Add CI tests and lints

### ISSUE THREAD

**Issue by lazulit3** [lazulit3/sea_skipper#1]
Some initial CI checks that would be nice to add are:
- `cargo clippy` lints
- `cargo test` (against `examples/axum_example` would be good, as there's tests there)
- `cargo fmt --check` (checks for formatting/style)

**Comment by Jean-BaptisteC** [comment]
Can you assign me on issue ?

**Comment by lazulit3** [comment]
Sure thing, thanks!
